---
- name: Set up development environment
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - zsh
          - tmux
          - sway
          - curl
          - git
        state: present

    - name: Create a local bin directory
      file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    - name: Download Neovim AppImage
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
        dest: /usr/local/bin/nvim.appimage
        mode: '0755'

    - name: Extract Neovim if no FUSE
      shell: |
        ./nvim.appimage --appimage-extract
        cp squashfs-root/usr/bin/nvim /usr/local/bin/nvim
        chmod +x /usr/local/bin/nvim
      args:
        chdir: /usr/local/bin

    - name: Clone and install WezTerm
      shell: |
        git clone --depth=1 https://github.com/wez/wezterm.git
        cd wezterm
        ./get-deps
        ./build
      args:
        executable: /bin/bash
