---
- name: Set up development environment
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - neovim
          - zsh
          - tmux
          - sway
          - curl
          - git
        state: present


    - name: Clone and install WezTerm
      shell: |
        git clone --depth=1 https://github.com/wez/wezterm.git
        cd wezterm
        ./get-deps
        ./build
      args:
        executable: /bin/bash
      when: ansible_distribution == "Ubuntu"
